name: get

version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  get_it: ^5.0.6
  rxdart: ^0.25.0
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
